### ISSUE TITLE
Can you release a version?

### ISSUE THREAD

**Issue by daixianceng** [russ666/yii2-countdown#1]
Can you release a version to make the composer install it?

**Comment by Chidex77** [comment]
Yes, this is a usefull widget but I can't install it. Composer always fails and complains about stable version!! 

Kindly help me resolve this, so we can install it with Composer !!!!

**Comment by russ666** [comment]
hi, I did it

**Comment by Chidex77** [comment]
Thanks, Please what do we type to download with Composer ? It is not shown on your widgets page.

Do I type : Composer.phar require "russ/666/countdown" "dev-master" 

or : Composer.phar require "russ/666/countdown" "*" 

or: Composer.phar require "russ/666/countdown" "2.0" 

Please, kindly specify what to type for composer!

Expecting your response.

Once more, Thanks for your widget

**Comment by russ666** [comment]
readme updated
