### ISSUE TITLE
NOT counting down

### ISSUE THREAD

**Issue by osnwach** [russ666/yii2-countdown#2]
@russ, I have just inserted the widget in my view file, it is displaying 00:00:00. But it is not counting down.

Please, how can i make it to start counting down ?

The code i used is:
                     <?php
                      echo \russ666\widgets\Countdown::widget([
                        'datetime' => date('Y-m-d H:i:s', time() + 2500),
                        'format' => '%H:%M:%S',
                         'events' => [
                        'finish' => 'function(){location.reload()}',
                         ],
                        ])

```
                  ?>
```

**Comment by russ666** [comment]
i just try your code, it works

**Comment by osnwach** [comment]
Did you add anything to above code? 

In my own case it just displays 00:00.

It does not display any time, and it does not count down !!

**Comment by russ666** [comment]
hm.. strange
try to specify datetime param as string (ex. 2015-08-27 11:20:00), maybe some trouble here

**Comment by osnwach** [comment]
Got it working with this code:

$mytime = date('Y/m/d H:i:s', time() + 14500);

echo \russ666\widgets\Countdown::widget([
    'datetime' => $mytime,
    'format' => '%M:%S',
    'events' => [
        'finish' => 'function(){location.reload()}',
    ],
])

The above code is working now !

I discovered that datetime should be in this format:

 'datetime' => "2016/08/24",

Thanks for the widget !!
