### ISSUE TITLE
How to add my html tag?

### ISSUE THREAD

**Issue by xdendev** [russ666/yii2-countdown#3]
Hi!
How to override or add html tag.
For example.
default:
<!span id="w0">01 02 23 12 84 20 34 10<!/span>
i needed:
 <!div id="countdown_dashboard">
        <!div class="dash weeks_dash">
            <!span class="dash_title">weeks<!/span>
            <!divclass="digit">0<!/div>
           <!div class="digit">1<!/div>
       <!/div>
<!/div>
Thanks.

**Comment by russ666** [comment]
at now it's not possible. I can add it at few days, if you still need it. Or you can make pull request)

**Comment by xdendev** [comment]
blya:(

**Comment by dignityinside** [comment]
Can you please add this feature!

**Comment by russ666** [comment]
@dignityinside hi. you could set any html in format param. Example:
```
echo \russ666\widgets\Countdown::widget([
    'id' => 'some-id',
    'datetime' => date('Y-m-d H:i:s O', time() + 1000),
    'format' => '\<span style=\"background: red\"\>%M</span>:%S',
    'tagName' => 'span',
    'events' => [
        'finish' => 'function(){location.reload()}',
    ],
])
```
