### ISSUE TITLE
Using with moment js.

### ISSUE THREAD

**Issue by Maximilan4** [russ666/yii2-countdown#4]
I suggest you to use moment.js with countdown, because server can be in one timezone, but client in another. In which case countdown does not work, because client time is larger than server time.

You can use moment js by this way:
`$script = "
               var countdownTo = moment.tz('{$this->datetime}','Europe/Minsk');
";
$script.= 'jQuery("#' . $this->id . '").countdown(countdownTo.toDate(), function(e) {$(this).html(e.strftime("' . $this->format . '"))})';`

**Comment by russ666** [comment]
ok. i'll try to fix this issue tonight

**Comment by russ666** [comment]
i found a solution. you just can add an date with timezone, and this issue will be solved. for example: `Y-m-d H:i:s O`.
